---
name: acceptance

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          always-auth: false
          node-version: 24.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Docker acceptance test
        run: pnpm test:docker

      - name: Run Docker Compose acceptance test
        run: pnpm test:docker:compose

      - name: Run Docker persistence acceptance test
        run: pnpm test:docker:persistence

      - name: Run Docker S3 file storage acceptance test
        run: pnpm test:docker:s3-storage
